version: '2.3'
services:
  odoo:
    image: odoo:latest
    container_name: odoo
    depends_on:
      - db
    ports:
      - "80:8069"
    restart: always
    #expose:
    #  - "8069"
    volumes:
      - ./odoo-web-data:/var/lib/odoo
      - /var/run/docker.sock:/var/run/docker.sock
   # environment:
   #   - db_host=odoo-db
   #   - HOST=odoo-db
      # - VIRTUAL_HOST=sub.odoo.com
      # - VIRTUAL_PORT=8069
      # - LETSENCRYPT_HOST=sub.odoo.com

  db:
    image: postgres:14
    container_name: db
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./odoo-db-data:/var/lib/postgresql/data/pgdata

#networks:
#  default:
#    external:
#      name: erp-network
